### ISSUE TITLE
Conda build failing due to missing typing_extensions in recipe

### ISSUE THREAD

**Issue by michaelcdevin** [wavespectra/wavespectra#118]
The [typing_extensions](https://github.com/python/typing_extensions) package was added as a dependency to `pyproject.toml` in 6e01f3f, but this dependency was never added to [wavespectra-feedstock](https://github.com/conda-forge/wavespectra-feedstock) to update the conda-forge build. This is causing `python -m pip check` to fail in an environment with wavespectra added, which is [breaking the conda build for our marine energy optimization software](https://github.com/conda-forge/wecopttool-feedstock/pull/26) (which depends on wavespectra) unless we limit the version to <3.15. It looks like this is what is causing the CI failures in the recent PRs of the wavespectra-feedstock repo as well.

I created https://github.com/conda-forge/wavespectra-feedstock/pull/18 to add typing_extensions and fix the issue.

**Comment by rafa-guedes** [comment]
Thank you @michaelcdevin for this. The recipe is broken with the Windows it looks though (which is the main reason why the conda recipe was created since the library did not install on Windows due to the Fortran compilation). Are you able to have a look at that issue please? Happy to merge that once that is fixed.

**Comment by rafa-guedes** [comment]
@michaelcdevin this specific issue has been solved in v4. The typing_extension library isn't used in wavespectra anymore. From `v4.0.2`, wavespectra should also install directly from pip. We haven't updated it to v4 in conda-forge yet though because the build is failing on macos so we may want to have a look at that before. In any case the typing_extension issue isn't relevant anymore so I'll close this issue and the feedstock pull request.

**Comment by michaelcdevin** [comment]
Excellent, good to hear this has been resolved!
