### ISSUE TITLE
MetOcean or here

### ISSUE THREAD

**Issue by JohnCHarrington** [wavespectra/wavespectra#26]
Not really an issue, I was just wondering why there are 2 versions of this code that both seem to be active (and have many of the same contributors), and which I should use?

**Comment by rafa-guedes** [comment]
The main developers left the company and started this repository to keep the open source project alive. They opted to keep their version instead of everyone contributing to the same codebase. We are not contributing to their version anymore, the reason you may still see commits from us there is because they have been merging some of our work into their repository. It is your choice which version to use.

**Comment by JohnCHarrington** [comment]
Fair enough, I'll stick to this one then, thanks!
