### ISSUE TITLE
constructing SpecArray vs SpecDataset - results are different

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#43]
If I understand it correctly then there are two ways of constructing a SpecArray.

1. Creating it from a DataArray via SpecArray(da)
2. Getting it from a SpecDataset via dset.spec

yet the two of them give me different results.

Consider the following snippet.

Step 1, invent some spectral data
```python
import numpy as np
import matplotlib.pyplot as plt
from wavespectra import SpecArray, SpecDataset
import xarray as xr

dir_bin_width = 10
dirs = np.arange(0,360,dir_bin_width)

start_freq = 0.03125
freq_resolution = 0.0078125
n_frequencies = 37
freqs = [(start_freq + i * freq_resolution) for i in range(0, n_frequencies)]
freqs = np.array(freqs)

# invent a spectrum
s_head = 1 + np.sin(np.deg2rad(dirs))
s_freq = 1 - np.cos(freqs * 6.24 / np.max(freqs))
spec = np.outer(s_head, 0.1*s_freq)


plt.figure()
plt.imshow(spec)
plt.title('input data')
```

![image](https://user-images.githubusercontent.com/34062862/118200670-46b8cc00-b488-11eb-93d7-18ca54eee10e.png)

Make a data-array:
```python
da = xr.DataArray(spec, dims = ('dir','freq'), coords={'dir':dirs, 'freq':freqs}, name = 'efth'
)
```

Option 1: Create a spec array from the data-array, then plot:

```python
sa = SpecArray(da)

plt.figure()
sa.plot()
plt.title('SpecArray constructed from DataArray')
```

![image](https://user-images.githubusercontent.com/34062862/118200774-841d5980-b488-11eb-965d-8a779e989a28.png)

Option 2: Create a dataset, then use the .spec property:

```python
dset = da.to_dataset(name = 'efth')
dset.spec.plot()
plt.title('DataSet constructed from DataArray, then extracted spec')
```

![image](https://user-images.githubusercontent.com/34062862/118200832-a44d1880-b488-11eb-9197-80428eb79069.png)

**Comment by RubendeBruin** [comment]
The strange thing is:

if I plot the DataSet a second time, then the plot is ok. So it may actually have something to do with the plotting rather than the construction.

```python
sa = SpecArray(da)

plt.figure()
sa.plot()
plt.title('SpecArray constructed from DataArray');
```

![image](https://user-images.githubusercontent.com/34062862/118229339-6a970480-b4be-11eb-8998-b341c95c3ec3.png)

```python
sa.plot()
plt.title('Plot again')
```

![image](https://user-images.githubusercontent.com/34062862/118229383-7c78a780-b4be-11eb-87c5-97a540f54fe5.png)

**Comment by rafa-guedes** [comment]
A SpecArray should not be constructed by instantiating the SpecArray class but simply importing the class into your session, e.g.:

```
from wavespectra import SpecArray
.
.

da = xr.DataArray(spec, dims = ('dir','freq'), coords={'dir':dirs, 'freq':freqs}, name = 'efth')
plt.figure()
da.spec.plot()
```

![spec](https://user-images.githubusercontent.com/7799184/118416559-6b20dc80-b704-11eb-89c9-ed2e710d34f6.png)

If the accessor class is imported, the accessor will be "attached" to your data array or dataset, as long as [the conventions](https://wavespectra.readthedocs.io/en/latest/conventions.html) are respected (variable and coordinate names, etc). This is basically what the input plugins do - they import the SpecArray /SpecDataset objects, open the dataset from each file format, format so it respects these conventions, and return the formatted dataset which will have the accessor attached. Simply `import wavespectra` instead of explicitly importing the accessors also works.

That been said, there is some known issues with the plotting, with unexpected behaviour sometimes happening when calling some plotting functions repeated times. We need to do some work to fix those.

**Comment by RubendeBruin** [comment]
Thanks for the clarification. Will see if I can add it to the docs somewhere.
