### ISSUE TITLE
I can't install it with pip without errors

### ISSUE THREAD

**Issue by Crissan85** [wavespectra/wavespectra#52]
I try to intall it in a command windows with 'python setup.py install' in the directory with the files, but error always occurs.
(pip is up to date).

'pip install -r requirements/extra.txt' works fine.

I had the 64 bit version of MinGW installed and the binaries are on the Windows PATH environment variable.

**Comment by rafa-guedes** [comment]
The pip install does not behave well on Windows because of the fortran watershed partitioning code. However there is a conda recipe recently created by @RubendeBruin so `conda install -c conda-forge wavespectra` should work. Your other option is installing the [pure-python](https://github.com/wavespectra/wavespectra/tree/pure-python) branch which has watershed written in python instead of fortran. It is significantly slower when processing large datasets but it should work on Windows.
