### ISSUE TITLE
wavespectra Conda and pip install problems 

### ISSUE THREAD

**Issue by slowtoaccept** [wavespectra/wavespectra#63]
Tried: conda install -c conda-forge wavespectra and got this:
ERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::openssl-1.1.1n-h8ffe710_0'.
Rolling back transaction: done
[Errno 13] Permission denied: 'C:\\Users\\slowt\\Anaconda3\\envs\\tide\\Library\\bin\\libssl-1_1-x64.dll' ()

Using conda 4.12.0.
Same error with pip install wavespectra
Using pip 22.0.4 and python 3.8

Fortran SSL related?

**Comment by slowtoaccept** [comment]
After several attempts and several hours,  windspectra successfully installed after I installed Windows 10 OpenSSL 3.0.2 and rebooted. Don't know if that helped as a newbie.

**Comment by rafa-guedes** [comment]
Hi @slowtoaccept,

wavespectra did not initially support Windows due to problems in compiling the Fortran module required by the Watershed partitioning code. @RubendeBruin has recently set up the conda recipe which allowed installing it on Windows more easily. I am not a Windows / conda user myself though so I am not sure why this problem happened. @RubendeBruin do you have some ideas here please?

**Comment by RubendeBruin** [comment]
installing from conda should not require any compilations on the target machine. This report looks like insufficient write rights. Can be because the dll is in use by another program. This can have many sources: incorrect path settings, other programs running at the same time that are using the file, etc.
