### ISSUE TITLE
spec.stats fails for partitioned spectra

### ISSUE THREAD

**Issue by DrakonianMight** [wavespectra/wavespectra#73]
Hi Team, 
I am currently using version 3.10 on Linux, python version 3.8 (installed via conda).

I get an error message when I try and split the spectrum and then calculate the statistics.
Looks like it is specifically caused by the tp and dpm methods from testing.
ws = wavespectra.read_ww3('my ww3 file')
ws.spec.stats(["hs", "hmax", "tp", "tm01", "tm02", "dpm", "dm", "dspr"], fmin = 1/10)

causes the following error.
![wavespectra](https://user-images.githubusercontent.com/46990198/192921369-854afa7d-83f8-489f-a82d-4229c3f01ab4.PNG)

**Comment by rafa-guedes** [comment]
Hi @DrakonianMight 

I can't seem to be able to reproduce this issue.

Within the `spec.split` method (which is called within `spec.stats` by providing either `fmin` or `fmax` to split the spectra first), an extra frequency `fmin` and/or `fmax` can be appended if these are not present in the `freq` coordinate. This could cause trouble because by appending it, the `freq` coordinate becomes chunked in the spectra which would cause the error you are seeing if trying to calculate some stat defined as an xarray ufunc (such as tp or dpm for example). We have fixed this issue in the past by providing the [rechunk argument](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/specarray.py#L196) in `spec.split` which defaults to `True` and ensures `freq` is always a single chunk in order to avoid this situation.

So I'm not sure why you are still seeing this. I did test it on `wavespectra-3.10` and was still not able to reproduce the problem. Can you please check if the `rechunk` argument is available in the `spec.split` method from your local install? Do you see this problem if you try this example using one of the test files provided such as [ww3file.nc](https://github.com/wavespectra/wavespectra/blob/master/tests/sample_files/ww3file.nc)? If so, could you send send the output of `pip freeze` from your environment?

**Comment by rafa-guedes** [comment]
In the meanwhile you can probably achieve what you are trying by splitting the spectra first, rechunking manually and then calculating the stats, e.g.:

```
ws = wavespectra.read_ww3('my ww3 file')
ws_split = ws.spec.split(fmin=1/10).chunk({"freq": -1})
ws_split.spec.stats(["hs", "hmax", "tp", "tm01", "tm02", "dpm", "dm", "dspr"])
```

**Comment by DrakonianMight** [comment]
Hi @rafa-guedes, 
Awesome thank you, that alternative method worked as suggested. 
I can see that the `spec.split` method does have that 'rechunk=True' argument. 
I continue to get the same error with the example file you provided. 
I will attempt a fresh environment install on another box (I have limited permissions on the one I am using, which may be a contributing factor). I'll let you know how I go.
Thanks again.
