### ISSUE TITLE
conda and PyPi packaging

### ISSUE THREAD

**Issue by cmichelenstrofer** [wavespectra/wavespectra#74]
We are trying to use this package as part of a [pseudo-spectral code for control co-design of wave energy converters](https://github.com/SNL-WaterPower/WecOptTool). But there are some issues with installing it. 

- The conda-forge package is out of date. See: metocean/wavespectra#44, metocean/wavespectra#13 
- The pip package requires having NumPy installed already. This is an easy fix. See: metocean/wavespectra#31

What this means is that although we can install all other dependencies through our pip installation, we have to **ask users to install wave-spectra as a separate step**, by itself. 

We are very interested in keep using this package and are **willing to help set this up** if needed. In our tool we use GitHub actions so that when we tag a new release in GitHub it automatically creates the PyPi package (and soon the conda-forge package). Maybe we can help set this up for wavespectra too.

@rafa-guedes, @RubendeBruin I have seen both of you comment on similar issues over at metocean/wavespectra so maybe you have some thoughts? Also thanks for creating this package, it is pretty cool and we are excited about using it in our project. But why are there two versions anyways? metocean has their own version which is also actively developed but they don't even package it. How do the two version differ? Thanks in advance!

**Comment by rafa-guedes** [comment]
Hi @cmichelenstrofer,

thanks for your comments and your suggestions, we will welcome your contribution if you are willing to help with the numpy dependency problem or any other features.

The conda-forge is out of date indeed. @RubendeBruin has set up the conda install some time ago so wavespectra could be installed on Windows but I think that requires manually merging some pull requests upon new PyPi releases. Will look into that.

The reason for the two versions is because the main developers left the organisation where the library was originally hosted in but there was no agreement unfortunately to unify the efforts outside of that organisation. This version is intended to be the focus of broader community efforts.

**Comment by RubendeBruin** [comment]
Version v3.11.0 was failing builds on conda
Version v3.12.0 does work. I just merged that update into the feedstock, so it should soon be available on conda-forge.

About the two versions of the same package: yeah, that is kinda confusing. I'm not sure what the fundamental difference is between the two packages.

If it is impossible to bring them back together then we could opt for a split into a core-package (specarray) and supporting functions (input, output, specparts).

One of the things that we (I) could do it make a separate package for specpart and place that on conda-forge and pypi. That would leave both wavespectra packages as pure python which would make installation on machines without fortran compiler a lot easier.

**Comment by cmichelenstrofer** [comment]
Thanks both for the quick reply and action on the `conda` packaging! I will submit a PR for improving the `pip` package (so that it doesn't fail if `NumPy` is not pre-installed). 

Regarding Fortran, we have no strong preference. We already use other packages that need Fortran ([capytaine](https://github.com/mancellin/capytaine)). The key thing is to have a `conda` package (which has pre-compiled binaries) in addition to a `pip` package. To install via `pip` you need the compilers, but there's always the easier `conda` option which doesn't.   

Sorry to hear that such disagreement exist but I'm glad you have created and maintained this community version. :)

**Comment by rafa-guedes** [comment]
The two versions originated from the same original code but since 2019 or so they have been split and there has been no collaborative efforts to try and keep them consistent. I don't know how much they would differ at this stage. I would not be in favour of yet another split I don't think in order to separate components of the library into another package.

@cmichelenstrofer it is good to know you are using wavespectra as a requirement in your other package because we have been working on several new features and are planning a major release soon that will bring some breaking changes - hopefully for the better. We will try and notify it here before we do it so you and others can be prepared before upgrading.

**Comment by cmichelenstrofer** [comment]
Oh I would be curious what features you are adding! And yes, I appreciate the heads up.
