### ISSUE TITLE
Replace deprecated numpy.distutil to build the watershed fortran module

### ISSUE THREAD

**Issue by rafa-guedes** [wavespectra/wavespectra#96]
The watershed partitioning in wavespectra is defined from [Fortran code](https://github.com/wavespectra/wavespectra/tree/master/wavespectra/specpart) modified from the WW3 src code. There is a python equivalent in the [pure-python branch](https://github.com/wavespectra/wavespectra/tree/pure-python) however it is a lot slower so we keep the fortran version in master.

The fortran module is [built in wavespectra using numpy.distutil](https://github.com/wavespectra/wavespectra/blob/master/setup.py) which is deprecated and has been removed in python 3.12. We need an alternative way to build it so wavespectra can be installed in python >= 3.12. [This page](https://numpy.org/doc/stable/reference/distutils_status_migration.html) suggests a couple of alternatives to replace numpy.distutil.

We would appreciate anyone willing to implement these changes :)

**Comment by RubendeBruin** [comment]
I did some tests with the meson-python alternative.

https://github.com/RubendeBruin/specpart/tree/meson

it is building and uploading to pypi without complaints but the the produced binary errors when I try to load it.

**Comment by RubendeBruin** [comment]
I've created a new package containing only specpart here: https://github.com/RubendeBruin/specpart

It currently runs (using meson) and builds wheels for windows.

I think it is good to separate specpart from wavespectrum as it makes development much easier on machines (windows) that do not have a fortran compiler. At the moment people like me can not easily work on wavespectra locally because we can not build the package.

**Comment by rafa-guedes** [comment]
Cool @RubendeBruin. As mentioned in https://github.com/wavespectra/wavespectra/issues/114#issuecomment-1981818340 we are currently working on trying to rewrite the watershed fortran code in C. If that works with similar performance we will ditch the fortran dependency altogether. Our preference is to keep the watershed code in wavespectra as it is a key component of the library.

**Comment by RubendeBruin** [comment]
Hi @rafa-guedes , I fail to see how switching to C would solve the issues with compilers on windows. Unless there are other issues with the fortran package that I'm not aware of I would stick with "if it aint broken don't fix it".

Corrrect me if I'm wrong but specpart seems to be a pretty constant factor in the package. It hasn't changed since it was added to the repository 7 years ago.

During that time it has been giving headages to people who wanted to adopt wavespectra. Separating it would not harm wavespectra in any way and would make maintainance, adoption and CI or wavespectra a lot easier as it would become a pure-python package.

So unless you are planning to add other compiled (c, c++) parts to wavespectra I would like to ask you to reconsider. I don't mind (at all!) to transfer the "ownership" of the repository and pypi package to the same people as wavespectra if that would help.

**Comment by rafa-guedes** [comment]
Hi @RubendeBruin separating the watershed code won't really solve the issue given it will still be a dependency which will have to be installed (it isn't a matter of ownership, the fortran code is in fact taken from from WW3). Writing it on C on the other hand will allow using python bindings and get rid of any fortran dependencies so yes it should definitely make it easier to work on Windows we hope.

**Comment by RubendeBruin** [comment]
Hi @rafa-guedes , well maybe I'm just doing it the wrong way.... 

# Steps that I would take to contribute to wavespectra

1. create a new python environment using either venv or conda
2. fork wavespectra on github, create a new branch
3. check out the branch to my local machine
4. install all the dependancies using either pip or conda
5. add the directory containing the wavespectra folder to the python path (add to sources in pycharm)
6. start using the checked out version of wavespectra, make contributions to the source

This is the point where I run into difficulties. I can not use the locally cloned copy because the compiled parts are not part of the source. So I need to manually work around it (replace specpart with a dummy for example) or do an inplace build, the latter of which requires a compiler.

Having the compiled parts in a separate package completely voids these issues as it would simply have been installed together with the other dependancies such as xarray.

On the other hand, if the packages need eachother (for example if specpart would use wavespectra for testing) then splitting them would be difficult. But as I understand specpart is used by wavespectra and not the other way around.

**Comment by rafa-guedes** [comment]
Hi @RubendeBruin as I said before we are working to remove fortran compilation altogether from the picture so this will hopefully be easier soon for you and others willing to contribute.

**Comment by rafa-guedes** [comment]
The fortran watershed module has been replaced by C in v4.0.0. numpy.distutils is no longer used which means wavespectra can now be used in python3.12, and can also be installed locally in development mode.
